apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cGQi8e537KpacDJJ2APK6WyElFKbYd5nl0RtsGHszaQwcxSbRPDAuA==,iv:JI43K/SFYIzlhLfgw24Z9BEbpI+Ne2QsLwgDQ1OHQ2Q=,tag:RozKZ01+txVVhC0EJElRIQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b3BmTk12Lzl3N2ZuamlH
            djRBRGNxZU5yL01yZVV3M1d4bnUzdkZidlVNClZRbnhZSm1kTnhmTDRlekJ4VnVw
            UEV4eG5rZ1RkdWFxMVpCUHpnbmI4encKLS0tIEFXc0sxZ3YrWkJxUEhpUlRHUlZr
            MFlJYlRWYWlzZTVnbDRlNFhMRjFZSlUKErB9zujtKhFJP8DnjUeCwhZAgvpfZoFm
            ua15HrZhcIJUGwRScFg+3+UEQVhxgB20coT348IDS/69KSix2isbLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:21:20Z"
    mac: ENC[AES256_GCM,data:3qqegvGyY4IFwEqwlxnpyG7yDuwSXZnqZo/9nIwubC4QF9+F6RrWH6jBChTHZVCY1oasuOiiJHq+NbqAHE7zU3LtfKDkmptd9p7xfiQ2F3xt9OcT5nnH/IU/qPD0D+QmDYfGe5BEp+sr56Nc1S+6c5fAFwC7PyuYjFotMQCJZ8w=,iv:pJxkLMuU84LPeBQceOB/I3LCidNg1kIANFEIAzHpwEg=,tag:fZgzknhF5qkarge83PWQbA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
