apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:yMdKbu5s7JlyxqHPd9Rteh2LjaSEbGiXHnzqmyu1PDbvtFovI4dDug==,iv:P9B2Al8jsug0nfiaHbRSfFz0Djm68phv2VHJXJ7q8x4=,tag:QxQ7eGm9c8caRyHtEOoYNQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSktkMStNeG9uSUd3Vkl6
            Z25iRHNvandaU3I0RkErck10SVEyWTRXekRvCnMzY1RiK2ZXREUyM2hFOUVQQ2Uz
            bFBtQUdqODBsQU1aSUZoQ1pXaDMvbFEKLS0tIFJ6dGF1TUtWSmdkdE1lKzNPVTVG
            ZDVpTVVjVmU2NVFYN2l5ekFmRWp5RXMKF63j+SnzfNwNQ1ZZBlMYGOI2zi+qQtPF
            TbwQ+paIAnvYn3PFQv3/pwuFYQpN1j5PPRD9hYVib28RUcfndXnMdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T19:17:03Z"
    mac: ENC[AES256_GCM,data:z1v09D01crLOxm1GVZ9I8vS3MSryw5cKwtdKcYrEfxBCtA1q5NShqrLuG6n2Twk8HDlKihgmblD0AHNdSX78G5ROhzR77AbELUq+CppQECXr38vDZLSekw1j6hOy4UwKLfWg1Tq1eXXeMhVCL4N6w8movT6GunuaJUOSY1TwL/4=,iv:iz008jgdGV/5B/F4Hek9rpYeWy+ZgXRMYURAkaPOoS0=,tag:8yy2CaiLP48ht/gTyW61xQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
