apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:skkIJWac8/issGc3JI7T8zVQAi85HGGA8v3Mj0lkZ/57NtC3TCCV5w==,iv:LrsZgRPLnsJHCNCYFfPuTWdIJ4ghPI872SaS9oEsK+w=,tag:G/Nd7JRZGIWSuBpSSKjdBQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneXhLdVpRc3lMZVgrQWxV
            R0R5eW10NXJSMTAyNFZscjZuTEoxUjNMY1RzCjBURmJOcGtnQ1hFUDJOenN3RHZF
            NUc0TUVBT2xjRHdNTFdRakVyZnYyRlkKLS0tIHk3b2lBNUo1dUdxR0NCdEo5Z1E0
            YmJFNU00M1RIS0VtSFNjeU5uVWZEWHMKmhKJjjqTi0YN/jFKCYqy4msRUHvYg2am
            xnYYm4tpGQxnqY6ZqdKdkbJfS4PQruZLh9HRETO02Rbp2TksWtwRaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:56:08Z"
    mac: ENC[AES256_GCM,data:yjSL7fII86c4c5SXGx3KRPjQNE/P9o0z1zPviPCwdMX8Vp+XDzY5IvFjnY8nXPgZF45cba50kOY9FeiCvihy/fulAdsj6l6At6QwkWpgKEsvU/TIwssrZUzRDG3G2qvRP+LlMBPIedkVubC3190NP9/P8NNddwhdDkG4fmADT+E=,iv:+nLSU2azcpQEs1sndmi9i1mAYoalrpLS2KBKCwMLHzg=,tag:n3A/qB/gta1GIM6lYbyyLw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
