apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - loki-datasource.yaml
  - dashboards/logs-lens.yaml
  - dashboards/pod-logs-dashboard.yaml
