---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: grafana
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        uid: loki
        url: http://loki-gateway.loki.svc.cluster.local
        jsonData:
          maxLines: 1000
          tlsSkipVerify: true
        isDefault: false