apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: loki
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 17.4.3
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deploymentMode: Monolithic
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
        accessModes:
        - ReadWriteOnce
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          memory: 3Gi
    monitoring: {}
    analytics:
      reporting_enabled: false
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: fs
      storageConfiguration: {}
      auth_enabled: false
      limits_config:
        ingestion_rate_mb: 100
        ingestion_burst_size_mb: 200
        max_log_size_per_line: 512000
        volume_enabled: true
      schemaConfig:
        configs:
        - from: '2024-04-01'
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
      storage_type: filesystem
    read:
      enabled: false
      replicas: 0
    write:
      enabled: false
      replicas: 0
    affinity:
      podAntiAffinity: disabled
    backend:
      enabled: false
      replicas: 0
