apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:r30Ahbjor5Slp9oEzK4ya1Xp7mYdcW0uQazpSu0kZ3CFBiyaIcvemgqy7mg2xytQ5PMLN2F8RIQL2EV+gvVepQbQ9NsXpMNOiuqg7stcn9k6PnWNWmT5F6cESoH11NqyLanFotP4wmmcWLXXxai1HHlK9orTitcd5I+3ztUCfNXyQFLq+sEjYsKebv0YntFXXJ3TO+z6oB0mk8Kq6YayfpJIA86YppNro3jvMSAoMsoIsfYP76O62UJM6VlANRIBCU4IMIfPWiP2ABis0BfgDaTTkrxUQrODPgNZMhUVClom5fMXodhuXawm3lYuXs0FKRU6Vma9jZuUv0pUgomjXpBjqvpXL0blmyKtUdQjOhBVe4BXuEEwqbF6RTaPUCyN,iv:gSMEtQsyPkE+HIOMVZX23lEXkM1kV7cn6Y1vEMT3Xwk=,tag:XhvQz9QZIFMKXMlg2Mrmzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:je6YuiOcOpKRJiYCs0VG4Ub1kXms2WlxQqEB2yyE37nGSP2GiZUS3D0tRyhPOcwZ/vHYtUEW3Td9MVbkHHP74Df9rdo6q2zlefesC5iL04iI3SdfNvAtmsKo6+7Wt8tjqScOILsMcOw0fFhcyqlBmcUAIgVdlQyhbxi+cM3ALqHoZZeeOGuVch5TxPbMhLFNDA65OWTD+iPKwxzvCuEXTDp03QN8HZqPqn4a6IOiYAmjtC1TLCHnLlyzki7f6QN7INbumsgI3U4BO0DvTQ==,iv:rhCyyF+WneksXEeWCKw8tVHvzOWDYiBrlrneP0pfMms=,tag:wLuxNesjgWy6ORo/PQwnlA==,type:str]
    known_hosts: ENC[AES256_GCM,data:E3NP2okRckpgQtXUMRvXj28enRhf7TUBiJH2H2+LQUwJJXv2VLiGFiTfPY46WiQaLhD5czPwAzwcv6KIP4QdWxv7DxAeq00NeiDi52xHRMkwuvk00fYQKbxH66Xgl5lvtJ77f3MchHaX0Q+TrTyXhTbBrUIALCHgfCauneo6Rp+Z3MGCsOHKHl+zIVq+tc+QxKwRkAWWpdlBKatOXFojPzwTRT0pFxY6ZKHR,iv:aGNckd2l36dvin02KeNLAw6yQhF9pcQGIf4ESMhV5g8=,tag:KXVcCu1M+FrMnl6RhHtpgA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNmpCcW4zMS9BVDVMM2Nw
            Y3AvYnRxRXJMTkk0OG44NnNlb3FRVisvZG44Cm9STHd0L0RkZ215Mm1IK1BEbVJx
            ajlUcmFWZGhDMFVpVEViSUNwUEdOVEkKLS0tIGYwaVJrY21TVDhYbkU0VVRFbko0
            Q2h3Q3JhcG5KdTdpVVFUQnljdURKcncKaYumFT6x+x1iGJ36KR+4KKJKBY6JQ+2L
            0U9v33+B6oW0Qbp3biBMzwC/llYV3ZoD6nZZ9BcIdfbn54rJ5dkaUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:31:51Z"
    mac: ENC[AES256_GCM,data:0bwB+sBy7ZmjUdv3qguDgGuj6z7Y6R7QHH5fPFwx2ZENtxp9SAqyg+hyXc9GKaCO0RI1XsaCHMJJOLcDEwyqGInbUsRoG/LDNU++oErQAAJl9XkBtWcB8GJqVcYqU62YcAv300qnslb2YPQCQi+FCXwU41tWryN8AWJEHOQF6Mg=,iv:Og5ROeO/TQo/7lxizJblBRYAgrvlKbBSqFhnTTvym/0=,tag:XxgwTOLouxJlZyKHK0SWRA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
