apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4RxtQ/5MEOcpA70L4VlPG8NCKfH0siRWRtLP2CRpkUrBM6tz1l+1CR2Ny0hwVoaIRwjotNqTXv/8W2VEBXgPkK5boLKj2LwmReTVsVX30K2hilhQt5EOrnIG1Eft5tVMPKTbfVQt5K4WVtLiouEP98EkJ45CcLe0nKZlNYeLu2G3A4wFB3KsQO5duMGXEUFe3JkqOoWg8Ydox+c33EsFuC9Ao3VIgDrCmOsnscKw9j1GKmR83zo+Z4R3nGdHZzGa21rQ3BWw7nyxtHA/LbtqkGoXQ2UP0XqwYPz9Q2Jg5dSZpaHULJxO3CKUYalgGlXV5jYS7MFbA4880koc7m+xSnatZZtRk9jzzrdF+x1qfg4rM60EOHPaGCTzxbZHnl2X,iv:4BEKufU9Uxjamqvf2suvGjosr/0TDVVIAAeMrLNyJjk=,tag:zEZQLpiReFuV+rJeNYZfNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:dj4/nuyNbjHg0eWRrZCFQIHmVQcZgAN36yRIcsq+ZkQpiVX4gXu+RFlR5gBHA18QUDEyd7LNPZ7dRvGeoOflavLpEnJL8MGAs9swudxNrlKPV5Sg0wKn4ma0v4Wq1Vio5w25UNWy9AAq9YDvYy73xvVobt5m2YXuY64cFKTlZfkR51YsQXVZmgEPBf9fig+L72tW+IsXIT7AtiHwxjAXsaK4rn1kOY9N2THmxukgrWvgd33Q5kCW4KUMtqn/bFAZQrbyelfbeYpL06s7AA==,iv:dRs5LQUq+smAs/5vuzj8xUKVtRP9t/4iPMqZY3bIRnk=,tag:VPLKx9GPQe2HJaMuOWey/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:02DFOXkKIulJDEzPpzMBj09WnPcV0zdw9EZes6NCv4KEW57ygyyl5sOCZa98v8ugdvNHRlIOAt0I8+bcATURKIfjKXSVBfjSOEJkm3ixqGqgOlprzVy9OtsmZvHYpjyG1UX0ArOStNgGT7GAt0cqpfhEWlNnfE1dNk7l8md6fVIh0Jpy+sLMy0bg9RiXCyzcnc1Kjg8tWk4TCwtzijGXjAhoY8rnIUM1Ct6z,iv:AMHbSXPInwPFAiqCGnSTWZhPOYXOQh5YcZ9TVnP1cig=,tag:JlN3QSrD91HsRMATfgMcvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb2l1blBjdFJIU0dKdWN5
            NlhBSW5Hc1dqbXNITmNLSi9KL1BpSTNwTFJVCk54eGV2VUw1dmV2S05Fcmw2SHVr
            SWs1V1A3VTArcUlJcGtGUVhNWnk1VlUKLS0tIDJnVS9sR3JFM0JKc3YvVEE2Ump0
            VEpSelpIVzFBNGlGVFkxM1pScEg1NGsKL1q5AAjcGn0BZcyy5d8HYVTptc0ImYj0
            ffyTZqlB9zzuMBO17ix98BOA7qm6PDl64YCORnEb4NXjAPy41idxUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T14:31:50Z"
    mac: ENC[AES256_GCM,data:Ba6rmcshvJ1gaYt/wsL9rB+novMhavYsqqoqICM6CpxiFx7ZwOlctxiFQ/u8SYgnLUYWKSiVkCjBZYiUsgCLZ/A+Bxy+OQ+MEZ0sZ5jW/jaYwDBjx36y1NZLTe93tJOUkokIy30Z8izkJyXL9Fmw2vqHxuwjckmlMgzgdnlQi9U=,iv:yiVmoEj5na3gFHIRF/B5u0mmGseQWCSkNZGCsPG5wJ4=,tag:Ajm2QbgMFjbplJVeOrcyJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
