apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1t1/chhXmwdD92vFd4xUtZS3PGibxBeUdVN5zpbRBpt/gsZwt64EyyPlTLEg13aEUXi9UjUdpVlLthxtQ82wCtZbzbhHKKif31WYpmKNtLDx9daspxETr07H5sE9MTXeoLTQGgUmo+cuon5Y4GuXDOGOvW7x5Wem/Va9hr5WUidrRHEuPrUxMTywhUx8FGwu4kNttRbruL5r5IdWfZ6/jqYw1bN1Mjg8kJrvVomLxVS48McO9UQme66m1nSRyNL8fPaIwZ4Ajowp/mpkBfZG6Dy5fPOl+hEpkJSd8gDjJ6auOKJpD49oZUXAD02ygFLdfLgiKLVstkU+KTQAOy99vD1bwf4FpfIMcNjrHQCtNoI/k4Nap31XUD6+6nETUIvt,iv:3a0UXS7g0OGdBFcel/mQ2xLlLkEH3ayiKEKH3wBugS4=,tag:CSeVuUknGNvVxiOcoQwKIA==,type:str]
    identity.pub: ENC[AES256_GCM,data:2qvrS6aDf8A6jhk5BG/o/qmYUISTPU/i5hnO0oZrjqOfSsrxez8F9pCeCfdYfb1mTJNX+ogNkPMitKa2P6JS2Ayv7V4I1VWuRKmijR1VvLakmsbRZUmafVm5p0Ds9V2WlG/o6uZEiVdThC9rWJahKyCHgY+H58QVmgImTwUwRnfouHSFseMFhcPbIkLzG2hrW6kVkxgedgNhJAbj8rv3DuJJV6QUPqRUJ5OXzHS+SE4e5gyKjlkkhk40jgsAPtit+hEKWQTTHe/18cL5Ug==,iv:H+YBgPNNvfavl/XKgoGTdbuAkU3oOPQJA5lH0sIM15I=,tag:QcYRRkvOk4mk56LHTQ7HzQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+c88/JnCPSQYu6++jjI0C+Frml7pKHCRJHc8XuonkYPmKB4jYFLzukKAge6eRqb+zeRQLxsC8AbsjnwAXK0lio6DbUAGJ2na2vtaqcen+/C9WSpm2Ifr1sp0bLJej/v11hBMCpquOcxSpgmy7aOxfG7RmHS3c8yewnb3293wz5hqs93S2/uXFQFr2GsCdZ26WKpIdS7GUHjgnU2g3StT7tiMZK7+3FnQ9jfz,iv:PRNWnqEtetcGX3RQDQiwV8jhTWlPOk0Pqb2qqRo5hAs=,tag:x/hdxxWlktbaPzabWCk1Ag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV0RJcnU1Uk5LS0xFbnAy
            dHg1dnZQaWxkd2tSZE5mL1VyWHNxQ0phS0FRCkVqSmVEeE5jSEI5d1FGTXphTFFk
            VE1vL0U4L1lySHRNRUg0TnZVYUJpM0kKLS0tIEd1K2gwa3Vka2lTVTFtYld3K3V2
            WHlQQXJkbHN4dElta3JadjBUdC9qU2MKTs3PvICYga+uweHZwFSHwTCobPcWoh/8
            LeIzDY1sqOO9VUVwMD3rVXHLwnXSnM8rFh5/I3Ba2pa4PG9eDGAZRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:38:30Z"
    mac: ENC[AES256_GCM,data:/kkpDx4z4Y/vQwnIXBQlkJZq7/vWxyEfROm/utFJjhbEJbxsV4nZQ8rjrSm2+ztN/0DS3T0a2m/+mKZtarY3+KDLjqJglLCaVVWbs/RntIDJECu9kgfQ7x6LCJuwxM5PpHaIMjyqMyCBlFPkUHsji0/ZUpNbpTfXPlhI+CoeeJA=,iv:Vg6lZTqHeigU2GIXXcawoZjezdhkimddopl9SlUf9rY=,tag:oJ9usXePFf5NyMg4FP+a7A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
