apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/pods/*/*.log
        Exclude_Path      /var/log/pods/logging/fluent-bit-*_*/fluent-bit/*/*.0.log
        Tag               kube.*
        DB                /run/fluentbit/fluent-bit.db
        DB.Sync           Normal
        DB.Locking        On
        Refresh_Interval  30s
        Ignore_Older      24h

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prune      kube
        Buffer_Size         50K

    [OUTPUT]
        Name                 loki
        Match                kube.*
        Host                 loki.loki.svc.cluster.local
        Port                 3100
        URI                  /loki/api/v1/push
        auto_kubernetes_labels "true"
        Retry_Limit          "5"
