apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/pods/*/*/*.log
        Exclude_Path      /var/log/pods/logging/fluent-bit-*_*/fluent-bit/*/*.0.log
        DB                /run/fluentbit/fluent-bit.db
        DB.Sync           Normal
        DB.Locking        On
        Refresh_Interval  30s
        Ignore_Older      24h

    [OUTPUT]
        Name                stdout
        Match               var.log.pods.*
        Format              json

    [OUTPUT]
        Name                 loki
        Match                var.log.pods.*
        Host                 loki.loki.svc.cluster.local
        Port                 3100
        URI                  /loki/api/v1/push
        tls                  false
        auto_kubernetes_labels true
        retry_limit          5
