{
 "title": "Log Lens",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Pod",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace, container) (count_over_time({namespace=~\"$namespace\"} [$__range]))",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({namespace=~\"$namespace\"} [$__range]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "table",
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}