---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: 21.14.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Helsinki
    global:
      stopAll: false
    deployment:
      N8N_HOST: "n8n.${DOMAIN_0}"
      N8N_EDITOR_BASE_URL: "https://n8n.${DOMAIN_0}"
    endpoints:
      WEBHOOK_URL: "https://n8n.${DOMAIN_0}/"
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "n8n.${DOMAIN_0}"
            paths:
            - path: "/"
              pathType: "Prefix" 
        integrations:
          traefik:
            enabled: false
            #auth
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                N8N_AI_ASSISTANT_BASE_URL: "https://n8n.${DOMAIN_0}"
                N8N_PROTOCOL: "https"
